# Generated by Django 3.2 on 2021-05-13 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submitshifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitShifts',
            new_name='SubmitShift',
        ),
    ]
