# Generated by Django 3.2 on 2021-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitshifts', '0002_rename_submitshifts_submitshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitshift',
            name='date',
        ),
        migrations.AddField(
            model_name='submitshift',
            name='day',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='submitshift',
            name='month',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='submitshift',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
