# Generated by Django 3.2 on 2021-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitshifts', '0003_auto_20210514_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitshift',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submitshift',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submitshift',
            name='year',
            field=models.IntegerField(),
        ),
    ]
