# Generated by Django 3.2 on 2021-05-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitshifts', '0005_auto_20210515_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitshift',
            name='fromtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitshift',
            name='totime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
