# Generated by Django 3.2 on 2021-05-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitshifts', '0007_auto_20210522_1300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submitshift',
            table='submitshifts',
        ),
    ]
