# Generated by Django 3.2 on 2021-06-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_name_staff_staff_name'),
        ('submitshifts', '0008_alter_submitshift_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitshift',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
