# Generated by Django 3.2 on 2021-05-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='staff_name',
        ),
    ]
