# Generated by Django 3.2 on 2021-05-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submitshifts', '0006_auto_20210515_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('modify_fromtime', models.IntegerField()),
                ('modify_totime', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitshifts.submitshift')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('am_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am1', to='createshifts.modifyshift')),
                ('am_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am2', to='createshifts.modifyshift')),
                ('am_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am3', to='createshifts.modifyshift')),
                ('pm_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm1', to='createshifts.modifyshift')),
                ('pm_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm2', to='createshifts.modifyshift')),
                ('pm_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm3', to='createshifts.modifyshift')),
            ],
        ),
        migrations.CreateModel(
            name='FlyerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('am_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer_am1', to='createshifts.modifyshift')),
                ('am_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer_am2', to='createshifts.modifyshift')),
                ('pm_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer_pm1', to='createshifts.modifyshift')),
                ('pm_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer_pm2', to='createshifts.modifyshift')),
            ],
        ),
        migrations.CreateModel(
            name='CounterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('am_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am1', to='createshifts.modifyshift')),
                ('am_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am2', to='createshifts.modifyshift')),
                ('am_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am3', to='createshifts.modifyshift')),
                ('am_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am4', to='createshifts.modifyshift')),
                ('am_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am5', to='createshifts.modifyshift')),
                ('am_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am6', to='createshifts.modifyshift')),
                ('pm_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm1', to='createshifts.modifyshift')),
                ('pm_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm2', to='createshifts.modifyshift')),
                ('pm_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm3', to='createshifts.modifyshift')),
                ('pm_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm4', to='createshifts.modifyshift')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createshifts.countershift')),
                ('flyer_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createshifts.flyershift')),
                ('kitchen_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createshifts.kitchenshift')),
            ],
        ),
    ]
