# Generated by Django 3.2 on 2021-05-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submitshifts', '0008_alter_submitshift_table'),
        ('createshifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifyshift',
            name='submit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submitshifts.submitshift'),
        ),
    ]
