# Generated by Django 3.2 on 2021-05-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createshifts', '0002_alter_modifyshift_submit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countershift',
            name='am_6',
        ),
        migrations.RemoveField(
            model_name='kitchenshift',
            name='am_3',
        ),
        migrations.AddField(
            model_name='countershift',
            name='pm_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm5', to='createshifts.modifyshift'),
        ),
        migrations.AddField(
            model_name='countershift',
            name='pm_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm6', to='createshifts.modifyshift'),
        ),
        migrations.AddField(
            model_name='kitchenshift',
            name='pm_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm4', to='createshifts.modifyshift'),
        ),
    ]
