# Generated by Django 3.2 on 2021-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createshifts', '0003_auto_20210529_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeshift',
            name='is_holiday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
